import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Layout/Header";
import { AuthProvider } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="py-8 flex m-auto w-full max-w-xl flex-col items-center min-h-screen dark:bg-dark-veryDarkBlue bg-light-lightGrayishBlue  bg-top bg-no-repeat ">
        <AuthProvider>
          <div className="bg-mobile-light dark:bg-mobile-dark md:bg-desktop-light md:dark:bg-desktop-dark w-full fixed top-0 left-0 bg-cover h-96 -z-10"></div>
          <Header />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
