@base_url = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjU0ZDI2ZDM0YmIxY2ZiNzQ1MzMxYTkiLCJ1c2VybmFtZSI6InVzZXIiLCJlbWFpbCI6ImVtYWlsQGVtYWlsLmNvbSIsImlhdCI6MTcxNjgzNDkyNSwiZXhwIjoxNzE2OTIxMzI1fQ.yqHQveEFfR9W1lgxt6b7MxSzroSc6rvD3a0uvgaq2JI

### Register
POST {{base_url}}/user/register
Content-Type: application/json

{
    "username": "user",
    "email": "email@email.com",
    "password": "password"
}

### Login
POST {{base_url}}/user/login
Content-Type: application/json

{
    "email": "email2@email.com",
    "password": "password"
}


### add task
POST {{base_url}}/task
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "task 1",
    "description": "task 1 description"
}
