@base_url = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiZW1haWwiOiJlbWFpbDJAZW1haWwuY29tIiwiaWF0IjoxNzE2NzQ2MDUyLCJleHAiOjE3MTY4MzI0NTJ9.DAyfDbdCTTbYq7jYz1RSXKyd5oP-9vxqAzWdftKyAdU

### Register
POST {{base_url}}/user/register
Content-Type: application/json

{
    "username": "user2",
    "email": "email2@email.com",
    "password": "password"
}

### Login
POST {{base_url}}/user/login
Content-Type: application/json

{
    "email": "email2@email.com",
    "password": "password"
}


### add task
POST {{base_url}}/task
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "userId": "user2",
    "title": "task 1",
    "description": "task 1 description"

}
